# Generated by Django 5.1.5 on 2025-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatingevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
