# Generated by Django 5.1.5 on 2025-01-30 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_cheatingevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingaudio',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='cheatingaudio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='audio_files',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='cheating_images',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='detected_objects',
        ),
        migrations.RemoveField(
            model_name='cheatingimage',
            name='description',
        ),
        migrations.AddField(
            model_name='cheatingaudio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='cheating_audios/'),
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_audios', to='proctoring.cheatingevent'),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctoring.student'),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_images', to='proctoring.cheatingevent'),
        ),
    ]
