# Generated by Django 5.1.5 on 2025-01-30 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0003_remove_cheatingaudio_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatingevent',
            name='detected_objects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proctoring.student'),
        ),
    ]
