# Generated by Django 5.1.5 on 2025-02-02 01:51

import django.db.models.deletion
import proctoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0005_alter_exam_timestamp_alter_student_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingevent',
            name='tab_switch_count',
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheating_events', to='proctoring.exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='gaze_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=proctoring.models.get_nepal_time),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('tab_switch', 'Tab Switch'), ('gaze', 'Gaze'), ('object_detected', 'Object Detected'), ('multiple_persons', 'Multiple Persons'), ('audio_detected', 'Audio Detected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=proctoring.models.get_nepal_time),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=proctoring.models.get_nepal_time),
        ),
    ]
