# Generated by Django 5.1.5 on 2025-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0006_remove_cheatingevent_tab_switch_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatingevent',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
