# Generated by Django 5.1.5 on 2025-02-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0007_cheatingevent_tab_switch_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='gaze_count',
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='audio_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('tab_switch', 'Tab Switch'), ('multiple_faces_detected', 'Multiple Faces Detected'), ('object_detected', 'Object Detected'), ('audio_detected', 'Audio Detected')], max_length=50, null=True),
        ),
    ]
