# Generated by Django 5.1.5 on 2025-02-06 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0008_remove_exam_gaze_count_cheatingevent_audio_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingevent',
            name='audio_file_path',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='tab_switch_count',
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
