# Generated by Django 5.1.5 on 2025-02-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0009_remove_cheatingevent_audio_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
