# Generated by Django 5.1.5 on 2025-02-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0010_alter_cheatingevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingevent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheating_events', to='proctoring.student'),
        ),
    ]
