# Generated by Django 5.1.5 on 2025-03-06 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0013_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 6, 55, 6, 59519)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 6, 55, 6, 59519)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 6, 55, 6, 59519)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 6, 55, 6, 59010)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 6, 55, 6, 57996)),
        ),
    ]
