# Generated by Django 5.1.5 on 2026-03-01 05:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctoring", "0017_alter_cheatingaudio_timestamp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cheatingaudio",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 10, 53, 34, 659366)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingevent",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 10, 53, 34, 658350)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingimage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 10, 53, 34, 658350)
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 10, 53, 34, 658350)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 10, 53, 34, 657173)
            ),
        ),
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Exam duration in minutes"),
                ),
                (
                    "exam_date",
                    models.DateTimeField(help_text="Scheduled exam date and time"),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Exam instructions for students",
                        null=True,
                    ),
                ),
                (
                    "total_marks",
                    models.IntegerField(
                        default=0, help_text="Total marks for the exam"
                    ),
                ),
                (
                    "passing_marks",
                    models.IntegerField(default=0, help_text="Minimum marks to pass"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is exam available for students"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(help_text="The question text")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice Question"),
                            ("subjective", "Subjective Question"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("option_a", models.CharField(blank=True, max_length=500, null=True)),
                ("option_b", models.CharField(blank=True, max_length=500, null=True)),
                ("option_c", models.CharField(blank=True, max_length=500, null=True)),
                ("option_d", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True, help_text="A, B, C, or D", max_length=1, null=True
                    ),
                ),
                (
                    "model_answer",
                    models.TextField(
                        blank=True,
                        help_text="Model answer for subjective questions",
                        null=True,
                    ),
                ),
                (
                    "marks",
                    models.IntegerField(default=1, help_text="Marks for this question"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of question in exam"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="proctoring.exampaper",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudentExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("total_marks_obtained", models.FloatField(default=0.0)),
                ("percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="proctoring.exampaper",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to="proctoring.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True, help_text="A, B, C, or D", max_length=1, null=True
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "answer_text",
                    models.TextField(
                        blank=True, help_text="Student's subjective answer", null=True
                    ),
                ),
                ("marks_obtained", models.FloatField(default=0.0)),
                (
                    "ai_feedback",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated feedback for subjective answers",
                        null=True,
                    ),
                ),
                (
                    "manually_overridden",
                    models.BooleanField(
                        default=False, help_text="Was this manually graded by admin?"
                    ),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="proctoring.question",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="proctoring.studentexamattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.FloatField()),
                ("marks_obtained", models.FloatField()),
                ("percentage", models.FloatField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A+", "A+ (90-100%)"),
                            ("A", "A (80-89%)"),
                            ("B+", "B+ (70-79%)"),
                            ("B", "B (60-69%)"),
                            ("C+", "C+ (50-59%)"),
                            ("C", "C (40-49%)"),
                            ("F", "F (Below 40%)"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Admin remarks", null=True),
                ),
                ("published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="proctoring.studentexamattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
