# Generated by Django 5.1.5 on 2026-03-01 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctoring", "0018_student_approval_status_student_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheatingaudio",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 12, 3, 15, 794905)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingevent",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 12, 3, 15, 794905)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingimage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 12, 3, 15, 794905)
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 12, 3, 15, 793908)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 1, 12, 3, 15, 793908)
            ),
        ),
    ]
