# Generated by Django 5.1.5 on 2026-03-07 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctoring", "0020_exampaper_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheatingaudio",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 7, 13, 56, 39, 7045)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingevent",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 7, 13, 56, 39, 6539)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingimage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 7, 13, 56, 39, 6862)
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 7, 13, 56, 39, 6290)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 7, 13, 56, 39, 5900)
            ),
        ),
    ]