# Generated by Django 5.1.5 on 2026-03-13 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctoring", "0022_alter_cheatingaudio_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheatingaudio",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 13, 18, 16, 43, 971644)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingevent",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 13, 18, 16, 43, 971644)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingimage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 13, 18, 16, 43, 971644)
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 13, 18, 16, 43, 971644)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 13, 18, 16, 43, 971644)
            ),
        ),
    ]
